authors:
  pellcorp:
    name: Jason Pell
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/274990
    url: https://github.com/pellcorp
  A3bagged:
    name: Chris v Liere
    description: Web / Graphic designer
    avatar: https://avatars.githubusercontent.com/u/181371480
    url: https://github.com/A3Bagged