nav:
    - 主页: index.md
    - 快速开始: 
        - 开始: getting-started.md
        - 语法: getting-started/markdown.md
        - 提示框: getting-started/admonitions.md
        - 代码块: getting-started/codeblocks.md
        - 自定义:
            - 设置示例: getting-started/setup.md
            - 使用 beta 标签: getting-started/tages.md
    - 博客: blog
    - 示例页面: 
        - cartographer.md
        - FAQ.md
    - 教程:
        - WebStack-Hugo 教程: tutorial/webstack-hugo-tutorial.md
